server:
  port: 8080
spring:
  application:
    name: Spring-AI-OpenAI
  ai:
    openai:
      api-key: ${MY_OPENAPI_KEY:UN_DEFINED_OPENAI_API_KEY}
  # application.properties in child module
  # This value is updated from SPring-AI-Apps-Paremnt <build> resources filtering config
  profiles.active: @spring.profiles.active@
