server:
  port: 8090

spring:
  application:
    name: Spring-AI-Ollama
  ai:
    model:
      chat: ollama
    ollama:
      chat:
        options:
          model: llama3.2:1b
      base-url: http://localhost:11434

  # application.properties in child module
  # This value is updated from SPring-AI-Apps-Paremnt <build> resources filtering config
  profiles.active: @spring.profiles.active@