logging:
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"

  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG