logging:
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"

  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG

spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: spring-ai-apps-user
    password: spring-ai-apps-user
    url: jdbc:h2:file:~/spring-ai-apps-chat-memory;AUTO_SERVER=true
  ai:
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
            schema: classpath:/schema-h2db-common.sql