CREATE TABLE SPRING_AI_CHAT_MEMORY (
   conversation_id VARCHAR(1000) NOT NULL,
    content LONGVARCHAR NOT NULL,
    type VARCHAR(50),
    "timestamp" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL

) ;

CREATE INDEX SPRING_AI_CHAT_MEMORY_CONVERSATION_ID_TIMESTAMP_MIX ON SPRING_AI_CHAT_MEMORY(conversation_id, timestamp) ;

ALTER TABLE SPRING_AI_CHAT_MEMORY ADD CON
 TYPE_CHECK CHECK (TYPE IN ('USER', 'ASSISTANT', 'SYSTEM'));